# Generated by Django 4.1.1 on 2022-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='croprecomend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil', models.CharField(max_length=30)),
                ('season', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='croprec',
        ),
    ]
