# Generated by Django 4.1.1 on 2022-10-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ff', '0002_croprecomend_delete_croprec'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='croprecomend',
            table='croprecomend',
        ),
    ]
